env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-starter-kit-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: dO39X6pnNLp8lXA0k4kpR+3dp/DsHxShlYohbz1cImmPPUahIHHQxUkYuPmXi8vqFZEXuTRnvmpWwGYb4HeSWcVFQ1Bs2nJPi/eUQiPXOIE4qsX3nxfs2e1YV6g0WhIeD4HZkTc+uXXfZ8XWT3GeyI7BCGUKbzQteq8BtTVhc7g=
  - secure: Qx4PBUHe+wPtVEf5w8hG0PvbCrY2oPg4j06YXUamVV91hNeu6cFICP0f4kiC5ajsp2AXPrPZhV1kbkkTZWGnErP5vFnt7fkmgP3hBQD8AB45mCCfhjuUveYgq4Z9cezNXtMyFuxrdgH93n/mRkpWfg4mj9UMP/fGyjcEz6ENTFQ=
  - secure: Y1mIYbRaFeukKXxTsG5k+Ohhjkq+3G9nw3WfOvZ7ctg+81VkoEj6Jh75PMaDykd1PpWvKCG/zTaxd+zQZzd+BhYdC97V6AQvW2GIbgFmfaDG2AmIW+YPCMGDMImf/CMcopqiIuCsxRpLr812fqTTYl2gjfxy4c5dYl39fFA5O/o=
  - secure: ElaGx4bmkwkqvYMRUjBywJH1YR966tL+4erY+XCwoEauywoQMamtQDkyO++g8Wx4OH13q7QmsW5ca26GZkyp5t7D0cY3umnvgzldaIkhaX8B9DFBHSzPA/Spj5NKdCTxzzjIZ0vb5y6J4ND9tqs6FWif+zYxitv1Ln0khobST3k=
  - secure: kUXxK3MqWC/WLa+7Q5yW03rvRPIJTPjtaK8CpG8XmzgmvJKaJEtC/5BvWtp4v49cRpazEcp8dgrdNmlGVlYwIT06G/0q1/X3D6AfuPL4ZIdNxf4BMgdfGJTElvSUVtQVPYifKL2BYVKhtnhKZtQ8GQTvyKpYFpQPH1uIBAUnriA=
  - secure: NmDeO7EvkmWbYC8wgWKCF4xIJs1gC8C5yUfHonC4quefi7JG4giHkmasijlB1YCBvmGkZGbJ9C0jOvnYKUG5MWFC9R2oEpr1dFvZJeu6lR7iYQQ8sJv3pyySXvN5fhl0n9sOomBEBBF7YgqKO/K4FMALWWpNLoEmA5sD9K3/nrQ=
  - secure: bbqjoFYRjjZxE6C4zE7fIb/zLWEcv+V1GwP3H2SKemPGLb+6nsZgD60kHVQMqWjzVYXOJvTNRmbfgFuMes24B+RLzXToF//0uixNI1KEp+Byz67N4jwp5+M0D/3zqVGSU3vnKmNazQSClybw9WKfYGhXRzRWJz8nhhzLJf58sYU=
language: python
python:
- '2.7'
install: pip install -r test/requirements.txt
before_script:
- gem install --version 0.8.9 faraday --no-ri --no-rdoc
- gem install travis-artifacts --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
